// Theme lists for each proficiency level
// A1: Absolute beginner - simple, concrete, everyday survival topics

export const A1_THEMES = [
  'introducing yourself and saying hello',
  'saying where you are from',
  'ordering coffee or tea',
  'asking what time it is',
  'buying a bus or train ticket',
  'asking where the bathroom is',
  'ordering breakfast',
  'asking how much something costs',
  'talking about your family',
  'saying what you do for work',
  'asking for directions to a place',
  'talking about the weather today',
  'ordering food at a café',
  'asking someone their name',
  'saying your phone number',
  'talking about your age',
  'buying fruit at a market',
  'asking where something is',
  'saying what day it is',
  'talking about your home',
  'asking someone to repeat something',
  'ordering lunch',
  'saying what you like to eat',
  'asking if a store is open',
  'talking about colors',
  'buying clothes in a shop',
  'asking for help in a store',
  'saying you are hungry or thirsty',
  'talking about pets',
  'asking what something is called',
  'ordering a sandwich',
  'saying thank you and goodbye',
  'talking about numbers',
  'asking where someone lives',
  'saying what time you wake up',
  'buying water at a shop',
  'talking about your nationality',
  'asking for the menu',
  'saying what you want to drink',
  'talking about your hobbies',
  'asking how to get somewhere',
  'buying a ticket',
  'saying what you do every day',
  'talking about your friends',
  'asking if you can pay by card',
  'ordering ice cream',
  'saying what languages you speak',
  'talking about the days of the week',
  'asking where the train station is',
  'buying bread',
  'saying what sports you like',
  'talking about your job',
  'asking for a glass of water',
  'saying what month it is',
  'talking about your city',
  'asking for the bill at a restaurant',
  'buying vegetables',
  'saying what music you like',
  'talking about transport',
  'asking if someone speaks English',
  'ordering pizza',
  'saying what you do on weekends',
  'talking about the seasons',
  'asking what the weather is like',
  'buying medicine at a pharmacy',
  'saying what time you go to bed',
  'talking about your country',
  'asking where to buy something',
  'ordering a meal',
  'saying what TV shows you watch',
  'talking about animals',
  'asking for coffee to go',
  'buying stamps at the post office',
  'saying what you study',
  'talking about your daily routine',
  'asking if a seat is free',
  'ordering drinks',
  'saying what you do in your free time',
  'talking about rooms in a house',
  'asking how to say a word',
  'buying a snack',
  'saying what books you read',
  'talking about months',
  'asking where the supermarket is',
  'ordering dinner',
  'saying your address',
  'talking about your schedule',
  'asking what food is available',
  'buying shoes',
  'saying what movies you like',
  'talking about telling time',
  'asking for directions on the street',
  'ordering at a fast food restaurant',
  'saying what you did today',
  'talking about feelings (happy, sad, tired)',
  'asking if something is available',
  'buying a gift',
  'saying what games you play',
  'talking about body parts',
  'asking for help with directions',
  'ordering at a bakery',
  'saying what you need to buy',
  'talking about furniture',
  'asking what someone likes',
  'buying a newspaper',
  'saying what colors you like',
  'talking about weather conditions',
  'asking where to find something',
  'ordering soup or salad',
  'saying what time you eat',
  'talking about classroom objects',
  'asking how someone is feeling',
  'buying groceries',
  'saying where you work',
  'talking about sizes (big, small)',
  'asking what day the store closes',
  'ordering meat or fish',
  'saying what you want to do tomorrow',
  'talking about money',
  'asking for a table at a restaurant',
  'buying flowers',
  'saying how old you are',
  'talking about prices',
  'asking where you can sit',
  'ordering dessert',
  'saying what you are doing now',
  'talking about cooking',
  'asking someone to speak slowly',
  'buying a drink',
  'saying what time you start work',
]

// A2: Elementary - familiar topics with preferences, simple planning, and basic opinions

export const A2_THEMES = [
  'planning a weekend trip with friends',
  'discussing your favorite restaurant',
  'making an appointment at the doctor',
  'talking about what you did last weekend',
  'choosing a gift for a friend',
  'discussing your favorite season and why',
  'planning a birthday celebration',
  'talking about your daily routine at work',
  'arranging to meet someone for coffee',
  'discussing what movies you like to watch',
  'shopping for furniture for your home',
  'talking about your last vacation',
  'planning an evening out',
  'discussing problems with your phone',
  'talking about your childhood home',
  'making plans to exercise together',
  'discussing your favorite type of music',
  'planning what to cook for dinner',
  'talking about learning to drive',
  'arranging a time to study together',
  'discussing different types of weather',
  'talking about your best friend',
  'planning a picnic in the park',
  'discussing why you like your job',
  'talking about your pet or pets you like',
  'making a shopping list together',
  'discussing your morning routine',
  'planning to visit a museum',
  'talking about sports you enjoy watching',
  'arranging a group dinner',
  'discussing your favorite TV series',
  'talking about problems at home',
  'planning a road trip',
  'discussing clothes you like to wear',
  'talking about your family traditions',
  'making plans for the holidays',
  'discussing how you get to work',
  'talking about books you have read',
  'planning activities for children',
  'discussing your school experiences',
  'talking about foods you cannot eat',
  'arranging to help someone move',
  'discussing your evening routine',
  'talking about places in your city',
  'planning a surprise for someone',
  'discussing problems with your car',
  'talking about games you played as a child',
  'making plans to visit relatives',
  'discussing your apartment or house',
  'talking about your work schedule',
  'planning what to do on a rainy day',
  'discussing recipes you know how to make',
  'talking about your favorite holiday',
  'arranging to go shopping together',
  'discussing hobbies you want to try',
  'talking about your experiences at restaurants',
  'planning a camping trip',
  'discussing festivals in your country',
  'talking about learning a new language',
  "making plans for someone's birthday",
  'discussing your typical breakfast',
  'talking about neighbors you know',
  'planning home improvements',
  'discussing concerts you have been to',
  'talking about your dream vacation',
  'arranging childcare with someone',
  'discussing technology you use every day',
  'talking about your favorite shops',
  'planning a party at home',
  'discussing public transport in your city',
  'talking about photographs you have taken',
  'making plans to go to the beach',
  'discussing allergies or health issues',
  'talking about furniture you need',
  'planning activities for a visitor',
  'discussing your sleeping habits',
  'talking about restaurants you want to try',
  'arranging a video call with family',
  'discussing clothes shopping preferences',
  'talking about your first job',
  'planning to adopt a pet',
  'discussing your hometown',
  'talking about good and bad weather',
  'making plans for New Year',
  'discussing apps you use on your phone',
  'talking about exercising and staying healthy',
  'planning to meet for lunch',
  'discussing your experiences with doctors',
  'talking about different types of homes',
  'arranging to go hiking',
  'discussing food delivery services',
  'talking about your favorite drinks',
  'planning what to wear to an event',
  'discussing traffic in your city',
  'talking about learning new skills',
  'making plans to watch a movie',
  'discussing household chores',
  'talking about birthday traditions',
  'planning a surprise party',
  'discussing favorite childhood memories',
  'talking about coffee and tea preferences',
  'arranging to go to a concert',
  'discussing gardening or plants',
  'talking about weekend activities you enjoy',
  'planning to redecorate a room',
  'discussing different cuisines',
  'talking about your siblings or relatives',
  'making plans for a free evening',
  'discussing problems at work or school',
  'talking about local events',
  'planning to take a class',
  'discussing travel experiences',
  'talking about saving money',
  'arranging a game night',
  'discussing your favorite places to relax',
  'talking about getting a haircut',
  'planning to try a new restaurant',
  'discussing online shopping experiences',
  'talking about fitness goals',
  'making plans to celebrate something',
  'discussing gifts you have received',
  'talking about your wedding or a wedding you attended',
  'planning lunch or dinner recipes',
  'discussing how you spend free time',
  'talking about places you want to visit',
  'arranging to do volunteer work',
  'discussing experiences with technology problems',
  'talking about your favorite time of day',
]

// B1: Intermediate - expressing opinions, discussing experiences, and abstract familiar topics

export const B1_THEMES = [
  'discussing the advantages and disadvantages of working from home',
  'talking about changing careers or jobs',
  'explaining how you balance work and personal life',
  'discussing a time you had a disagreement with someone',
  'comparing different ways to stay healthy',
  'talking about learning experiences that changed you',
  'discussing your views on social media use',
  'explaining why you chose to live in your current city',
  'talking about environmental issues in your community',
  'discussing the importance of family versus friends',
  'comparing traditional and modern ways of communication',
  'talking about a goal you are working towards',
  'discussing the role of technology in daily life',
  'explaining your opinion on online shopping',
  'talking about cultural differences you have noticed',
  'discussing ways to reduce stress',
  'comparing living alone versus living with others',
  'talking about memorable travel experiences',
  'discussing the benefits of learning languages',
  'explaining your views on healthy eating',
  'talking about how you make important decisions',
  'discussing the value of higher education',
  'comparing city life and countryside living',
  'talking about your favorite ways to spend free time',
  'discussing challenges of modern parenting',
  'explaining how you stay motivated',
  'talking about the impact of smartphones on society',
  'discussing your experiences with different types of transport',
  'comparing traditional books with e-books',
  'talking about volunteering or helping others',
  'discussing the importance of work-life balance',
  'explaining your opinion on climate change actions',
  'talking about adapting to new situations',
  'discussing the pros and cons of social networking',
  'comparing different education systems',
  'talking about maintaining long-distance relationships',
  'discussing your views on consumer culture',
  'explaining how you deal with difficult situations',
  'talking about the importance of physical exercise',
  'discussing changes in your hometown over time',
  'comparing different approaches to saving money',
  'talking about influences on your career choice',
  'discussing the role of art and culture in society',
  'explaining your opinion on work flexibility',
  'talking about experiences that taught you something',
  'discussing the effects of tourism on local areas',
  'comparing different generations and their values',
  'talking about the importance of hobbies',
  'discussing your views on public versus private healthcare',
  'explaining how you organize your daily schedule',
  'talking about adjusting to life in a new place',
  'discussing the benefits and drawbacks of renting',
  'comparing fast food and home-cooked meals',
  'talking about your relationship with technology',
  'discussing the importance of sleep and rest',
  'explaining your views on alternative medicine',
  'talking about dealing with work pressure',
  'discussing the value of cultural traditions',
  'comparing different types of entertainment',
  'talking about your experiences learning new skills',
  'discussing the importance of mental health',
  'explaining your opinion on fashion and personal style',
  'talking about the role of music in your life',
  'discussing challenges in maintaining friendships',
  'comparing online and face-to-face communication',
  'talking about your views on work benefits',
  'discussing the impact of advertising on consumers',
  'explaining how you prepare for important events',
  'talking about memorable meals or dining experiences',
  'discussing the pros and cons of owning pets',
  'comparing different approaches to time management',
  'talking about your experiences with healthcare',
  'discussing the importance of community involvement',
  'explaining your views on personal privacy',
  'talking about dealing with unexpected changes',
  'discussing the role of sports in society',
  'comparing different holiday traditions',
  'talking about your relationship with money',
  'discussing the benefits of reading',
  'explaining your opinion on remote education',
  'talking about adapting to new technologies',
  'discussing the importance of personal space',
  'comparing different celebration customs',
  'talking about your experiences with customer service',
  'discussing the value of professional networking',
  'explaining how you maintain work relationships',
  'talking about the role of news and media',
  'discussing challenges of balancing multiple responsibilities',
  'comparing different housing options',
  'talking about your views on sustainable living',
  'discussing the importance of setting boundaries',
  'explaining your opinion on career development',
  'talking about experiences with different cultures',
  'discussing the role of routines in daily life',
  'comparing different communication styles',
  'talking about your views on personal growth',
  'discussing the impact of weather on mood',
  'explaining how you handle conflicts',
  'talking about the value of different relationships',
  'discussing challenges in professional life',
  'comparing traditional and modern family structures',
  'talking about your experiences with public services',
  'discussing the importance of work satisfaction',
  'explaining your views on life-work integration',
  'talking about memorable life transitions',
  'discussing the role of exercise in well-being',
  'comparing different shopping preferences',
  'talking about your experiences with online services',
  'discussing the value of personal interests',
  'explaining your opinion on urban development',
  'talking about maintaining health as you age',
  'discussing the importance of financial planning',
  'comparing different travel styles',
  'talking about your views on education quality',
  'discussing challenges of modern communication',
  'explaining how you manage personal finances',
  'talking about the role of food in culture',
  'discussing your experiences with job searching',
  'comparing different leisure activities',
  'talking about your views on neighborhood development',
  'discussing the importance of personal achievements',
  'explaining your opinion on transportation options',
  'talking about adapting to seasonal changes',
  'discussing the value of life experiences',
  'comparing different problem-solving approaches',
  'talking about your views on professional training',
  'discussing the role of celebrations in life',
]

// B2: Upper-intermediate - nuanced debates, complex analysis, and sophisticated discussions

export const B2_THEMES = [
  'debating whether artificial intelligence poses more opportunities or threats to society',
  'discussing the ethical implications of genetic engineering and designer babies',
  'analyzing the impact of globalization on local cultures and traditions',
  'debating the effectiveness of universal basic income as a social policy',
  'discussing how social media algorithms influence public opinion and democracy',
  'evaluating the balance between individual privacy rights and national security',
  'debating whether universities should prioritize practical skills over theoretical knowledge',
  'discussing the role of capitalism in addressing climate change',
  'analyzing generational wealth gaps and their societal consequences',
  'debating the merits of meritocracy versus equal opportunity policies',
  'discussing how automation will reshape the future workforce',
  'evaluating the effectiveness of international organizations in solving global problems',
  'debating whether cultural appropriation can ever be acceptable',
  'discussing the psychological effects of constant digital connectivity',
  'analyzing the role of traditional media versus independent journalism',
  'debating the ethics of wealth accumulation in modern society',
  'discussing how urban planning affects social inequality',
  'evaluating different approaches to addressing homelessness',
  'debating whether space exploration is justified given problems on Earth',
  'discussing the implications of declining birth rates in developed countries',
  'analyzing the relationship between economic growth and environmental sustainability',
  'debating the role of government in regulating big tech companies',
  'discussing how migration patterns are reshaping national identities',
  'evaluating the effectiveness of different education philosophies',
  'debating whether traditional career paths are still relevant',
  'discussing the societal impact of declining religious participation',
  'analyzing the ethics of consumer culture and planned obsolescence',
  'debating the balance between free speech and preventing harmful content',
  'discussing how cultural narratives shape our understanding of success',
  'evaluating the long-term consequences of the gig economy',
  'debating whether tradition or progress should guide societal development',
  'discussing the role of empathy versus logic in moral decision-making',
  'analyzing how language shapes thought and cultural perspectives',
  'debating the effectiveness of punishment versus rehabilitation in justice systems',
  'discussing whether happiness should be a policy goal for governments',
  'evaluating the impact of tourism on cultural authenticity',
  'debating the role of standardized testing in education',
  'discussing how corporate influence affects political decision-making',
  'analyzing the relationship between individual freedom and social responsibility',
  'debating whether scientific progress always leads to human progress',
  'discussing the implications of increasing life expectancy on society',
  'evaluating different philosophical approaches to meaning and purpose',
  'debating whether economic sanctions are effective foreign policy tools',
  'discussing how confirmation bias affects our understanding of truth',
  'analyzing the role of art in political and social movements',
  'debating the ethics of performance enhancement in sports and academics',
  'discussing whether multiculturalism strengthens or weakens social cohesion',
  'evaluating the effectiveness of international climate agreements',
  'debating the role of emotion versus reason in effective leadership',
  'discussing how economic inequality affects democratic participation',
  'analyzing the impact of declining attention spans on learning and culture',
  'debating whether historical monuments should be preserved or removed',
  'discussing the ethics of using animals for scientific research',
  'evaluating different models of work-life integration in modern society',
  'debating whether objective truth exists or is socially constructed',
  'discussing how technological dependence affects human relationships',
  'analyzing the role of competition versus cooperation in human nature',
  'debating the effectiveness of affirmative action policies',
  'discussing whether economic growth should be prioritized over quality of life',
  'evaluating the impact of celebrity culture on societal values',
  'debating the role of government in promoting healthy lifestyles',
  'discussing how narrative framing influences perception of events',
  'analyzing the ethics of surveillance in public spaces',
  'debating whether cultural relativism or universal values should guide ethics',
  'discussing the implications of artificial intelligence in creative fields',
  'evaluating the effectiveness of grassroots versus institutional change',
  'debating whether expertise or popular opinion should guide policy',
  'discussing how nostalgia influences political and cultural movements',
  'analyzing the relationship between technological progress and human happiness',
  'debating the role of patriotism in an increasingly globalized world',
  'discussing whether cancel culture represents accountability or censorship',
  'evaluating different approaches to achieving gender equality',
  'debating the ethics of human enhancement technologies',
  'discussing how filter bubbles affect political polarization',
  'analyzing the role of luck versus merit in personal success',
  'debating whether economic systems should prioritize efficiency or equity',
  'discussing the implications of declining trust in institutions',
  'evaluating the effectiveness of various environmental conservation strategies',
  'debating whether cultural preservation or cultural evolution is more important',
  'discussing how language policies affect minority communities',
  'analyzing the ethics of predictive policing and algorithmic justice',
  'debating the role of suffering in human development and meaning',
  'discussing whether technological solutions can solve social problems',
  'evaluating the impact of corporate social responsibility initiatives',
  'debating the balance between individual autonomy and collective welfare',
  'discussing how media representation shapes cultural perceptions',
  'analyzing the relationship between democracy and economic development',
  'debating whether progress is linear or cyclical in human history',
  'discussing the ethics of intellectual property in the digital age',
  'evaluating different approaches to addressing mental health challenges',
  'debating whether human nature is fundamentally competitive or cooperative',
  'discussing how power dynamics affect interpersonal communication',
  'analyzing the role of ritual and tradition in modern secular society',
  'debating the effectiveness of market mechanisms in solving social problems',
  'discussing whether objectivity is possible in journalism and research',
  'evaluating the implications of extending human lifespan indefinitely',
  'debating the role of national sovereignty in addressing global challenges',
  'discussing how cultural narratives about aging affect society',
  'analyzing the ethics of economic incentives in addressing behavior',
  'debating whether diversity initiatives improve or complicate workplace dynamics',
  'discussing the implications of declining social capital in communities',
  'evaluating different philosophical approaches to environmental ethics',
  'debating whether technological advancement inevitably leads to job displacement',
  'discussing how framing effects influence decision-making and judgment',
  'analyzing the role of individual responsibility in systemic problems',
  'debating the effectiveness of international humanitarian intervention',
  'discussing whether authenticity is possible in the age of social media',
  'evaluating the impact of standardization on creativity and innovation',
  'debating the role of government in addressing economic inequality',
  'discussing how cultural differences in communication styles affect collaboration',
  'analyzing the ethics of using big data for behavioral prediction',
  'debating whether economic metrics adequately measure societal well-being',
  'discussing the implications of declining physical interaction on human development',
  'evaluating different approaches to balancing security and liberty',
  'debating whether moral progress exists or is culturally relative',
  'discussing how institutional structures perpetuate or prevent inequality',
  'analyzing the role of narrative and storytelling in shaping reality',
  'debating the effectiveness of incremental versus radical social change',
  'discussing whether human consciousness can be replicated artificially',
  'evaluating the impact of consumerism on environmental sustainability',
  'debating the role of empathy in effective policymaking',
  'discussing how cultural attitudes toward failure affect innovation',
  'analyzing the ethics of prioritizing local versus global responsibilities',
  'debating whether meritocratic systems truly reward merit or reproduce privilege',
  'discussing the implications of algorithmic decision-making on human agency',
]
